### ISSUE TITLE
预览网站

### ISSUE THREAD

**Issue by xrkffgg** [actions-cool/github-action-branding#1]
### 简介
github action branding 选择和预览

是 https://github.com/marketplace?query=issue 中 action 显示的 图标

在代码中使用

```
branding:
  icon: 'activity'
  color: 'red'
```

### 效果

- https://feathericons.com/  （原始显示，不适用于 github action 效果）
- https://github.com/haya14busa/github-action-brandings （icon 列表不同步）

### 参考

READM 中有 2 个 链接

#### card 参考
- https://codepen.io/abhishek747/pen/BbWKVa
- https://codepen.io/steveeeie/pen/NVWMEM   这个由于有多个 可能不太适用，看看就好
- https://codepen.io/42EG4M1/pen/ryoXyX 
- 也可类似于 zoo-issue-helper 那种
- 也可自行发挥

### 功能

- icons 列表
    - 名称获取，test.js 里有。icon 显示参照  feathericons  github 网站
    - 支持 输入筛选，类似于 feathericons 网站
    - 颜色方案可使用 github-action-brandings 中，默认随机，可选择颜色查看。不一定要下拉框，也可全部列出来切换选择。同时点击可复制颜色名称。
    - 支持点击图标复制图标 name
    - 注意 white yellow 背景时，图标为黑色，其他白色
    - 可在网页上显示 TIP。注明可点击 图标和颜色 可直接复制。
- ribbon
    - https://github.com/tholman/github-corners
    - https://github.com/codepo8/css-fork-on-github-ribbon
    - https://github.blog/2008-12-19-github-ribbons/
- 技术栈，不限 vue react html
- README 编写
- gh-pages 部署

**Comment by xrkffgg** [comment]
给你设了 admin，有时间再搞

**Comment by ajuner** [comment]
有空帮忙看看改改呗

**Comment by xrkffgg** [comment]
有点忙，你先部署到 gh-page，我就不用启动了

**Comment by xrkffgg** [comment]
color: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding

**Comment by xrkffgg** [comment]
### 可优项
- [x] title icon 网页
- [x] 背景白色 同 github marketplace
- [x] 颜色类型参考文档
- [x] 加 ribbon
- [x] gh-pages 自动化
- [x] 默认屏幕，呈现左右，把 颜色列表放在 右侧。input 支持 快捷 focus，显示 总数量，滚动时，input 固定最上。
- [x] 小屏，也可参考该网站布局
- [x] 随机按钮，点击一次，可再次随机一次。
- [x] 单个颜色点击第一次切换颜色，点击第二次复制颜色。
- [x] 看下有没 专门表示 可复制的 cursor
- [x] 标题样式应更吸引人 😂   ，名称为 GitHub Action Branding ，不应为 项目名
- [x] Readme 编写，可以截个最终效果图
