### ISSUE TITLE
Shows icons that are omitted from GitHub action branding

### ISSUE THREAD

**Issue by DenverCoder1** [actions-cool/github-action-branding#15]
Cool project, I came across this when looking to try out some icons, but I noticed the project includes icons that are not allowed by GitHub which makes the project a bit more difficult to use.

From https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon:
> Brand icons are omitted as well as the following:
> coffee	columns	divide-circle	divide-square divide	frown	hexagon	key meh	mouse-pointer	smile	tool x-octagon

## Possible solutions

One possibility could be to parse the JSON schema from https://json.schemastore.org/github-action.json to check that the icons are allowed in GitHub actions. 
A list appears to be maintained at that link and can be extracted with the query `$.properties.branding.properties.icon.enum`.

Alternatively, a list could be maintained independently which would probably be faster but potentially more effort to maintain. The list above can of course be omitted, as well as most icons tagged with "logo", the "target" icon seems to be the only exception as far as I can tell.

In case it helps, here is a list formed from taking the difference between the feathericons repo list and the enum appearing in the action schema:

```js
[
    "chrome",
    "codepen",
    "codesandbox",
    "coffee",
    "columns",
    "divide-circle",
    "divide-square",
    "divide",
    "dribbble",
    "figma",
    "framer",
    "frown",
    "github",
    "gitlab",
    "hexagon",
    "instagram",
    "key",
    "linkedin",
    "meh",
    "mouse-pointer",
    "pen-tool",
    "slack",
    "smile",
    "table",
    "tool",
    "trello",
    "twitch",
    "twitter",
    "x-octagon",
    "youtube",
]
```

**Comment by xrkffgg** [comment]
Thx we will fix

**Comment by ajuner** [comment]
site has been updated

**Comment by DenverCoder1** [comment]
Looks great :100:
