### ISSUE TITLE
交互改进？

### ISSUE THREAD

**Issue by xrkffgg** [actions-cool/github-action-branding#2]
你感觉有啥需要改进的地方吗？

**Comment by ajuner** [comment]
感觉是不是复制内容应该有个
```
branding:
  icon: 'activity'
  color: 'red'
```
这样的会稍微方便一点

**Comment by xrkffgg** [comment]
可行。。。

PC 端加吧，mobile  不加了。。

就在 右侧下方，原有的交互 逻辑不变。

下方加一个 textarea 点击哪个 icon or color 就换上。然后有一个 按钮 可以把整个复制出来

**Comment by xrkffgg** [comment]
mobile 记得隐藏

**Comment by xrkffgg** [comment]
我在想 框是不是放 颜色筛选的上面 好一点

**Comment by xrkffgg** [comment]
你试一下，截个图 发过来瞅瞅

**Comment by xrkffgg** [comment]
这个上面用 复制的里面加上 我们的网站，你看issue-helper  里

**Comment by ajuner** [comment]
![image](https://user-images.githubusercontent.com/53512912/109015769-71e51800-76f0-11eb-8f91-99c750ca6552.png)

**Comment by ajuner** [comment]
没展示地址  复制的时候才带出来

**Comment by xrkffgg** [comment]
背景感觉还是需要再调整调整。。。

![image](https://user-images.githubusercontent.com/29775873/109026706-ff2d6a00-76fa-11eb-822d-33f891583255.png)

文字可以做成有 颜色的

**Comment by xrkffgg** [comment]
你先提交到其他分支吧，走 PR

**Comment by xrkffgg** [comment]
才看到，都提了啊，那先这样

**Comment by xrkffgg** [comment]
外层样式参考这个 看看

https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=base16-dark&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false#

还有一点，random 时，点击能否直接展出来。

**Comment by xrkffgg** [comment]
在它的下方再展示 一个 新的按钮预览图如何？

**Comment by ajuner** [comment]
感觉不用吧  毕竟用户都自己点了要选择的了

**Comment by xrkffgg** [comment]
滚动后，视线离开当时选择的 icon ，就无法直观的看出当前选择的是啥了
